//! Windows native backend boundary.
//!
//! Raw Input device enumeration, observation-only capture, and `SendInput`
//! injection are implemented on Windows. Suppression remains deliberately
//! disabled: Raw Input identifies the originating device, whereas low-level
//! hooks can suppress an event but do not carry the same device handle.
//! Claiming per-device suppression before that correlation is proven could
//! strand local input.

#[cfg(any(windows, test))]
mod capture;
mod identity;
mod mapping;
#[cfg(any(windows, test))]
mod ownership;

#[cfg(windows)]
mod native;
#[cfg(not(windows))]
mod unsupported;

#[cfg(windows)]
pub use native::{
    probe_capabilities, WindowsDisplayBackend, WindowsInputBackend, WindowsOutputBackend,
};
#[cfg(not(windows))]
pub use unsupported::{
    probe_capabilities, WindowsDisplayBackend, WindowsInputBackend, WindowsOutputBackend,
};

use thiserror::Error;

pub use identity::derive_device_id;

/// Marker placed in every `SendInput` record generated by this backend.
///
/// A future low-level hook must compare `dwExtraInfo` against this value before
/// an event is admitted to routing. The value is intentionally pointer-width
/// safe so it works in both 32-bit and 64-bit processes.
pub const KVM_INJECTION_TAG: u32 = 0x4B56_4D31;

/// Maximum number of translated events waiting for the daemon callback.
///
/// The Raw Input message thread uses a non-blocking send. Motion/scroll beyond
/// this bound is dropped; key/button overflow terminates capture as an explicit
/// discontinuity. Both outcomes are reported through [`CaptureStatistics`].
pub const CAPTURE_QUEUE_CAPACITY: usize = 1_024;

/// Monotonic capture counters used by diagnostics.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct CaptureStatistics {
    /// Canonical events produced before bounded-queue admission.
    pub captured_events: u64,
    /// Events discarded because the callback queue was full.
    pub dropped_events: u64,
    /// Native packets that could not be represented safely in the shared model.
    pub untranslated_packets: u64,
    /// Raw Input keyboard packets presented to the translator.
    pub keyboard_packets: u64,
    /// Raw Input mouse packets presented to the translator.
    pub mouse_packets: u64,
    /// Keyboard packets rejected by conservative translation.
    pub untranslated_keyboard_packets: u64,
    /// Mouse packets that contained no representable motion, button, or wheel event.
    pub untranslated_mouse_packets: u64,
    /// Panics caught at the callback boundary.
    pub callback_panics: u64,
    /// Suppression requests ignored by the observation-only Raw Input layer.
    pub suppression_requests_ignored: u64,
    /// Capture generations stopped because a state transition could not be
    /// admitted to the bounded callback queue.
    pub capture_discontinuities: u64,
}

/// Availability of one native capability at the time it was probed.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityState {
    Available,
    /// Windows permits injection only into processes at an equal or lower
    /// integrity level; there is no process-wide permission to preflight.
    TargetDependent,
    NotImplemented,
    UnsupportedPlatform,
    Unavailable,
}

/// Snapshot of native capabilities used by onboarding and diagnostics.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WindowsCapabilities {
    pub device_enumeration: CapabilityState,
    pub input_injection: CapabilityState,
    pub display_enumeration: CapabilityState,
    pub device_aware_capture: CapabilityState,
    pub per_device_suppression: CapabilityState,
    /// Human-readable probe failures. Empty when all implemented probes pass.
    pub diagnostics: Vec<String>,
}

/// Errors produced at the platform boundary.
#[derive(Debug, Error)]
pub enum WindowsBackendError {
    #[error("the Windows backend is unavailable on this operating system")]
    UnsupportedPlatform,
    #[error("{feature} is not implemented: {reason}")]
    NotImplemented {
        feature: &'static str,
        reason: &'static str,
    },
    #[error("unsupported input payload: {0}")]
    UnsupportedInput(String),
    #[error("invalid input payload: {0}")]
    InvalidInput(&'static str),
    #[error("input capture is already running")]
    CaptureAlreadyRunning,
    #[error("Raw Input keyboard/mouse registration is owned by another backend instance")]
    CaptureRegistrationOwned,
    #[error("input capture thread failed: {0}")]
    CaptureRuntime(String),
    #[error("Windows API {operation} failed: {source}")]
    WindowsApi {
        operation: &'static str,
        #[source]
        source: std::io::Error,
    },
}
